/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'id' : bigint,
  'total' : bigint,
  'paymentMethod' : PaymentMethod,
  'customer' : Principal,
  'items' : Array<bigint>,
}
export type PaymentMethod = { 'creditCard' : null } |
  { 'cashOnDelivery' : null } |
  { 'crypto' : null } |
  { 'klarnaPayLater' : null } |
  { 'paypal' : null };
export interface RichProduct {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'imageURL' : string,
  'price' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToCart' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateCartTotal' : ActorMethod<[], bigint>,
  'calculateCartTotals' : ActorMethod<
    [],
    { 'tax' : bigint, 'total' : bigint, 'subtotal' : bigint }
  >,
  'clearCart' : ActorMethod<[], undefined>,
  'filterProductsByPriceCategory' : ActorMethod<[string], Array<RichProduct>>,
  'filterProductsByPriceRange' : ActorMethod<
    [bigint, bigint],
    Array<RichProduct>
  >,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<RichProduct>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<bigint>>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getOrderHistory' : ActorMethod<[], Array<Order>>,
  'getOrdersByUser' : ActorMethod<[Principal], Array<Order>>,
  'getProduct' : ActorMethod<[bigint], [] | [RichProduct]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeStore' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isProductInCatalog' : ActorMethod<[bigint], boolean>,
  'isStoreInitialized' : ActorMethod<[], boolean>,
  'placeOrderWithPaymentMethod' : ActorMethod<[PaymentMethod], bigint>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProducts' : ActorMethod<[string], Array<RichProduct>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];